### PR TITLE
Upgrade lein-npm to 0.5.0

### PR DESCRIPTION
**Pull request by roanosullivan**
Upgrade to get fix for [Issue 14 "resolve-in-jar-dep is a wee bit brittle"](https://github.com/RyanMcG/lein-npm/issues/14).

### CODE REVIEW

**Comment by jvandyke** [comment]
@myguidingstar Can you merge this please?

**Comment by myguidingstar** [comment]
I can no longer maintain lein-bower. Anyone wants to take it over?

**Comment by achernyak** [comment]
@myguidingstar We just started utilizing this library, and I would be happy to take over the maintenance.

**Comment by myguidingstar** [comment]
@achernyak  cool. I've added you to git repo. What's your clojars.org user btw?

**Comment by achernyak** [comment]
@roanosullivan I am closing this since it was resolved in #19

**Comment by hackeryarn** [comment]
@myguidingstar are you able to also add me to clojars so I can push the new release? Username is  [acher](https://clojars.org/users/acher).

**Comment by myguidingstar-zz** [comment]
Done. Thanks for your work

**Comment by hackeryarn** [comment]
Glad to help out! Thanks for getting me setup so quickly.

**Pull request closed without merging**
